### ISSUE TITLE
Bug: Application crashes with Assertion Failed in OpenCV

### ISSUE THREAD

**Issue by sabkx** [appventure-nush/TrackerV2#6]
![image](https://github.com/appventure-nush/TrackerV2/assets/107317973/90fac723-eca9-45e3-ac36-f9db15da2aeb)
![image](https://github.com/appventure-nush/TrackerV2/assets/107317973/a9272a8a-a7ec-42ce-b56a-54aecfc2eba0)
![image](https://github.com/appventure-nush/TrackerV2/assets/107317973/4272ffc1-31a0-460a-8d89-4f4f603ea55c)

Steps to reproduce the bug:
1. Open any video
2. Select Edge Detection, leave the default settings
3. Play the video until the end
4. Pause the video
5. Press the play button again
6. Press the pause button again. Now, the above error messages should appear

**Comment by jedlimlx** [comment]
ok this error has 0 consequences for the program actually functioning, its just OpenCV saying it reached the end of the video. I'll try and hide the error I guess

**Comment by sabkx** [comment]
thanks for the reply. ignoring it works.
